// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8b1u2rFIxmjuZPDDtpqaa1OBmJWRyPl8',
    appId: '1:1053720307757:web:c9ff3543b3cd739ea230a4',
    messagingSenderId: '1053720307757',
    projectId: 'travel-app-advanced',
    authDomain: 'travel-app-advanced.firebaseapp.com',
    storageBucket: 'travel-app-advanced.firebasestorage.app',
    measurementId: 'G-CHBRC28GS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqe55I-8zDlP0jHMUThoX23MwMNkT2pI',
    appId: '1:1053720307757:android:86305f941722de1da230a4',
    messagingSenderId: '1053720307757',
    projectId: 'travel-app-advanced',
    storageBucket: 'travel-app-advanced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugjwl1Z39AjaF6rYT-AIHP6Q-YxR-QHo',
    appId: '1:1053720307757:ios:96750d3449bedca6a230a4',
    messagingSenderId: '1053720307757',
    projectId: 'travel-app-advanced',
    storageBucket: 'travel-app-advanced.firebasestorage.app',
    iosBundleId: 'com.example.travelingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCugjwl1Z39AjaF6rYT-AIHP6Q-YxR-QHo',
    appId: '1:1053720307757:ios:96750d3449bedca6a230a4',
    messagingSenderId: '1053720307757',
    projectId: 'travel-app-advanced',
    storageBucket: 'travel-app-advanced.firebasestorage.app',
    iosBundleId: 'com.example.travelingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8b1u2rFIxmjuZPDDtpqaa1OBmJWRyPl8',
    appId: '1:1053720307757:web:ec5d9beb06e87d14a230a4',
    messagingSenderId: '1053720307757',
    projectId: 'travel-app-advanced',
    authDomain: 'travel-app-advanced.firebaseapp.com',
    storageBucket: 'travel-app-advanced.firebasestorage.app',
    measurementId: 'G-30RFET7F4H',
  );
}
